
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deploy
  labels:
    app: argo-app
    env: prod

spec:
  replicas: 3

  selector:
    matchLabels:
      app: argo-app
      env: prod

  template:
    metadata:
      labels:
        app: argo-app
        env: prod
        version: v1

    spec:
      containers:
        - name: argo-container
          image: karthikshetty1828/argo:7
          ports:
            - containerPort: 8080
